using System.Collections.Generic;
using UnityEngine;

public class ClankerController : MonoBehaviour
{
    [Header("Navigation")]
    public bool Active = true;
    public Vector3 TargetPosition;

    // ======================================================
// Path Following
// ======================================================

    [Header("Path")]
    public HeliPath ActivePath;
    public int PathIndex;
    public bool HoverNext;
    public bool HoverAtTarget;

    public float NodeAdvanceDistance = 20f;
    public float LookAheadDistance = 35f;

    [Header("Movement")]
    public float CruiseSpeed = 45f;
    public float MaxSpeed = 60f;
    public float MaxAcceleration = 10f;

    [Header("Hover")]
    public float HoverRadius = 15f;
    public float HoverExitRadius = 22f;
    public float HoverPositionGain = 0.45f;
    public float HoverVelocityGain = 1.6f;
    public float MaxHoverAcceleration = 5f;

    [Header("Lift")]
    public float Gravity = 9.81f;
    public float HoverLift = 9.81f;
    public float MaxLift = 30f;
    public float LiftResponse = 20f;

    [Header("Attitude")]
    public float MaxPitch = 22f;
    public float MaxRoll = 30f;
    public float MaxYawRate = 90f;

    [Header("Angular")]
    public float PitchAcceleration = 120f;
    public float RollAcceleration = 150f;
    public float YawAcceleration = 120f;
    public float AttitudeResponse = 0.5f;

    [Header("Drag")]
    public float ForwardDrag = 0.05f;
    public float SideDrag = 2.5f;
    public float VerticalDrag = 0.75f;

    [Header("Animation")]
    public Animator RotorAnimator;
    
    public Transform GunnerLeft;
    public Transform GunnerRight;
    public Transform GunLeft;
    public Transform GunRight;
    
    // Events
    public delegate void NodeReachedHandler(int nodeIndex);
    public delegate void PathCompletedHandler();
    public delegate void StartedHover();

    public event NodeReachedHandler OnHeliNodeReached;
    public event PathCompletedHandler OnHeliPathCompleted;
    public event StartedHover OnHeliStartedHover;

    //====================================================
    // Runtime
    //====================================================

    private Transform _tr;

    private Vector3 _velocity;
    private Vector3 _angularVelocity;

    private float _lift;

    private bool _hoverMode;
    private Vector3 _hoverHeading;

    /*
     * This is the ONLY command generated by the guidance system.
     *
     * It represents the thrust vector we wish the rotor to produce,
     * including gravity compensation.
     */
    private Vector3 _desiredThrust;

    /*
     * Desired aircraft orientation.
     */
    private Vector3 _desiredForward;
    private Vector3 _desiredUp;

    void Awake()
    {
        _tr = transform;

        _lift = HoverLift;

        _desiredForward = _tr.forward;
        _desiredUp = _tr.up;
    }

    void Update()
    {
        if (!Active)
            return;

        float dt = Time.deltaTime;

        if (dt <= 0f)
            return;

        Flight(dt);
    }

    public void SetTargetHover(Vector3 pos)
    {
        TargetPosition = pos;
        HoverNext = true;
        HoverAtTarget = true;
    }

    public void SetTargetPosition(Vector3 pos)
    {
        TargetPosition = pos;
        HoverNext = false;
        HoverAtTarget = false;
    }

    public void SetPath(HeliPath path)
    {
        ActivePath = path;
        PathIndex = 0;
        HoverNext = false;
        HoverAtTarget = false;
    }

    private void Flight(float dt)
    {
        UpdatePath();
        
        HoverAtTarget =
            ActivePath == null ||
            HoverNext;
        
        UpdateGuidance();

        ComputeDesiredThrust();

        ComputeDesiredOrientation();

        UpdateAngularMotion(dt);

        UpdateLift(dt);

        ApplyForces(dt);

        ApplyDrag(dt);

        Integrate(dt);
    }
    
    private void UpdatePath()
    {
        if (ActivePath == null)
            return;

        if (PathIndex >= ActivePath.Nodes.Count)
            return;

        Transform current =
            ActivePath.Nodes[PathIndex].transform;

        /*
         * Final node.
         */
        if (PathIndex == ActivePath.Nodes.Count - 1)
        {
            TargetPosition = current.position;
            HoverAtTarget = true;
            HoverNext = true;
            return;
        }

        Transform next =
            ActivePath.Nodes[PathIndex + 1].transform;

        Vector3 segment = next.position - current.position;
        float length = segment.magnitude;

        if (length < 0.01f)
        {
            TargetPosition = next.position;
            return;
        }

        Vector3 direction = segment / length;

        float along = Mathf.Clamp(
            Vector3.Dot(
                _tr.position - current.position,
                direction),
            0f,
            length);

        float lookAhead = Mathf.Min(
            along + LookAheadDistance,
            length);

        TargetPosition =
            current.position +
            direction * lookAhead;

        /*
         * Advance once we've progressed far enough along
         * the current segment.
         */
        if (along >= length - NodeAdvanceDistance)
        {
            PathIndex++;
            
            OnHeliNodeReached(PathIndex);

            if (PathIndex == ActivePath.Nodes.Count - 2)
            {
                HoverNext = true;

                if (PathIndex == ActivePath.Nodes.Count - 1)
                {
                    OnHeliPathCompleted?.Invoke();
                }
            }
        }
    }

    private void UpdateGuidance()
    {
        Vector3 horizontalError =
            Vector3.ProjectOnPlane(
                TargetPosition - _tr.position,
                Vector3.up);

        float distance =
            horizontalError.magnitude;

        if (!_hoverMode &&
            HoverAtTarget &&
            distance <= HoverRadius)
        {
            _hoverMode = true;

            OnHeliStartedHover?.Invoke();

            _hoverHeading =
                Vector3.ProjectOnPlane(
                    _tr.forward,
                    Vector3.up);

            if (_hoverHeading.sqrMagnitude < 0.001f)
                _hoverHeading = Vector3.forward;

            _hoverHeading.Normalize();
        }
        else if (_hoverMode &&
                 distance > HoverExitRadius)
        {
            _hoverMode = false;
        }
    }

    private void ComputeDesiredThrust()
    {
        if (_hoverMode)
            ComputeHoverThrust();
        else
            ComputeCruiseThrust();
    }

    private void ComputeCruiseThrust()
    {
        Vector3 toTarget =
            TargetPosition - _tr.position;

        Vector3 horizontal =
            Vector3.ProjectOnPlane(
                toTarget,
                Vector3.up);

        Vector3 direction =
            horizontal.sqrMagnitude > 0.001f
                ? horizontal.normalized
                : Vector3.ProjectOnPlane(
                    _tr.forward,
                    Vector3.up).normalized;
        
        Vector3 currentVelocity =
            Vector3.ProjectOnPlane(
                _velocity,
                Vector3.up);
        
        float distance = horizontal.magnitude;

        float desiredSpeed = CruiseSpeed;
            /*Mathf.Min(
                CruiseSpeed,
                Mathf.Sqrt(
                    2f * MaxAcceleration * distance));*/

        if (HoverNext)
        {
            /*
             * Constant deceleration:
             *
             * v² = 2ad
             */

            float brakingDistance =
                Mathf.Max(
                    0f,
                    distance - HoverRadius);

            desiredSpeed =
                Mathf.Sqrt(
                    Mathf.Max(
                        0f,
                        2f *
                        MaxAcceleration *
                        brakingDistance));

            desiredSpeed =
                Mathf.Min(
                    desiredSpeed,
                    CruiseSpeed);

            desiredSpeed =
                Mathf.Max(
                    desiredSpeed,
                    5f);
        }

        Vector3 desiredVelocity =
            direction * desiredSpeed;

        Vector3 desiredAcceleration =
            desiredVelocity - currentVelocity;

        desiredAcceleration =
            Vector3.ClampMagnitude(
                desiredAcceleration,
                MaxAcceleration);

        /*
         * Vertical guidance.
         *
         * This intentionally prioritizes maintaining altitude over
         * horizontal speed.
         */
        float verticalAcceleration =
            Mathf.Clamp(
                (TargetPosition.y - _tr.position.y) -
                _velocity.y,
                -MaxAcceleration,
                MaxAcceleration);

        _desiredThrust =
            desiredAcceleration +
            Vector3.up *
            (Gravity + verticalAcceleration);
    }
    
        private void ComputeHoverThrust()
    {
        Vector3 positionError =
            TargetPosition - _tr.position;

        Vector3 horizontalError =
            Vector3.ProjectOnPlane(
                positionError,
                Vector3.up);

        Vector3 horizontalVelocity =
            Vector3.ProjectOnPlane(
                _velocity,
                Vector3.up);

        Vector3 horizontalAcceleration =
            horizontalError * HoverPositionGain -
            horizontalVelocity * HoverVelocityGain;

        horizontalAcceleration =
            Vector3.ClampMagnitude(
                horizontalAcceleration,
                MaxHoverAcceleration);
        
        if (horizontalError.magnitude < HoverRadius * 0.25f)
        {
            horizontalAcceleration *=
                horizontalError.magnitude /
                (HoverRadius * 0.25f);
        }

        float verticalAcceleration =
            positionError.y * HoverPositionGain -
            _velocity.y * HoverVelocityGain;

        verticalAcceleration =
            Mathf.Clamp(
                verticalAcceleration,
                -MaxHoverAcceleration,
                 MaxHoverAcceleration);

        _desiredThrust =
            horizontalAcceleration +
            Vector3.up *
            (Gravity + verticalAcceleration);
    }

    private void ComputeDesiredOrientation()
{
    Vector3 desiredHeading;

    if (_hoverMode)
    {
        desiredHeading = _hoverHeading;
    }
    else
    {
        Vector3 horizontalVelocity =
            Vector3.ProjectOnPlane(
                _velocity,
                Vector3.up);

        if (horizontalVelocity.sqrMagnitude > 1f)
        {
            desiredHeading =
                horizontalVelocity.normalized;
        }
        else
        {
            desiredHeading =
                TargetPosition - _tr.position;

            desiredHeading.y = 0f;

            if (desiredHeading.sqrMagnitude < 0.001f)
            {
                desiredHeading =
                    Vector3.ProjectOnPlane(
                        _tr.forward,
                        Vector3.up);
            }
        }
    }

    if (desiredHeading.sqrMagnitude < 0.001f)
        desiredHeading = Vector3.forward;

    desiredHeading.Normalize();

    Vector3 headingRight =
        Vector3.Cross(
            Vector3.up,
            desiredHeading);

    if (headingRight.sqrMagnitude < 0.001f)
        headingRight = _tr.right;

    headingRight.Normalize();

    Vector3 horizontalThrust =
        Vector3.ProjectOnPlane(
            _desiredThrust,
            Vector3.up);

    float verticalThrust =
        Mathf.Max(
            0.1f,
            _desiredThrust.y);

    float forwardThrust =
        Vector3.Dot(
            horizontalThrust,
            desiredHeading);

    float lateralThrust =
        Vector3.Dot(
            horizontalThrust,
            headingRight);

    float maxForwardThrust =
        verticalThrust *
        Mathf.Tan(
            Mathf.Clamp(
                MaxPitch,
                0f,
                80f) *
            Mathf.Deg2Rad);

    float maxLateralThrust =
        verticalThrust *
        Mathf.Tan(
            Mathf.Clamp(
                MaxRoll,
                0f,
                80f) *
            Mathf.Deg2Rad);

    forwardThrust =
        Mathf.Clamp(
            forwardThrust,
            -maxForwardThrust,
            maxForwardThrust);

    lateralThrust =
        Mathf.Clamp(
            lateralThrust,
            -maxLateralThrust,
            maxLateralThrust);

    /*
     * Fade very small horizontal corrections so the helicopter
     * does not sit at an exaggerated permanent tilt.
     */
    Vector2 horizontalRequest =
        new Vector2(
            forwardThrust,
            lateralThrust);

    if (horizontalRequest.magnitude < 1f)
    {
        float scale =
            horizontalRequest.magnitude;

        forwardThrust *= scale;
        lateralThrust *= scale;
    }

    Vector3 limitedThrust =
        Vector3.up * verticalThrust +
        desiredHeading * forwardThrust +
        headingRight * lateralThrust;

    /*
     * Keep thrust direction and magnitude consistent.
     * UpdateLift() reads _desiredThrust.magnitude, so it must use the
     * same limited vector that determines the requested orientation.
     */
    _desiredThrust = limitedThrust;
    _desiredUp = _desiredThrust.normalized;

    _desiredForward =
        Vector3.ProjectOnPlane(
            desiredHeading,
            _desiredUp);

    if (_desiredForward.sqrMagnitude < 0.001f)
    {
        _desiredForward =
            Vector3.ProjectOnPlane(
                _tr.forward,
                _desiredUp);
    }

    if (_desiredForward.sqrMagnitude < 0.001f)
    {
        _desiredForward =
            Vector3.Cross(
                _tr.right,
                _desiredUp);
    }

    _desiredForward.Normalize();
}

    private void UpdateAngularMotion(float dt)
    {
        Quaternion desiredRotation =
            Quaternion.LookRotation(
                _desiredForward,
                _desiredUp);

        Quaternion error =
            Quaternion.Inverse(
                _tr.rotation) *
            desiredRotation;

        error.ToAngleAxis(
            out float angle,
            out Vector3 axis);

        if (angle > 180f)
            angle -= 360f;

        Vector3 desiredAngularVelocity =
            Vector3.zero;

        if (Mathf.Abs(angle) > 0.001f &&
            axis.sqrMagnitude > 0.000001f)
        {
            axis.Normalize();

            desiredAngularVelocity =
                axis *
                (angle /
                 Mathf.Max(
                     0.05f,
                     AttitudeResponse));
        }

        Vector3 angularAcceleration =
            (desiredAngularVelocity -
             _angularVelocity) /
            Mathf.Max(
                dt,
                0.0001f);

        angularAcceleration.x =
            Mathf.Clamp(
                angularAcceleration.x,
                -PitchAcceleration,
                 PitchAcceleration);

        angularAcceleration.y =
            Mathf.Clamp(
                angularAcceleration.y,
                -YawAcceleration,
                 YawAcceleration);

        angularAcceleration.z =
            Mathf.Clamp(
                angularAcceleration.z,
                -RollAcceleration,
                 RollAcceleration);

        _angularVelocity +=
            angularAcceleration * dt;

        _angularVelocity.y =
            Mathf.Clamp(
                _angularVelocity.y,
                -MaxYawRate,
                 MaxYawRate);

        _tr.rotation *=
            Quaternion.Euler(
                _angularVelocity * dt);
    }
    
        private void UpdateLift(float dt)
    {
        /*
         * Rotor produces the magnitude of the requested thrust.
         * Attitude determines where that thrust points.
         */

        float targetLift =
            Mathf.Clamp(
                _desiredThrust.magnitude,
                0f,
                MaxLift);

        _lift = Mathf.MoveTowards(
            _lift,
            targetLift,
            LiftResponse * dt);

        if (RotorAnimator != null)
        {
            RotorAnimator.SetFloat(
                "Speed",
                (1.5f * _lift + 5f) /
                MaxLift);
        }
    }

    private void ApplyForces(float dt)
    {
        /*
         * Rotor thrust.
         */
        Vector3 liftAcceleration =
            _tr.up * _lift;

        /*
         * Gravity.
         */
        Vector3 gravityAcceleration =
            Vector3.down * Gravity;

        _velocity +=
            (liftAcceleration +
             gravityAcceleration) * dt;
    }

    private void ApplyDrag(float dt)
    {
        Vector3 forward =
            Vector3.Project(
                _velocity,
                _tr.forward);

        Vector3 right =
            Vector3.Project(
                _velocity,
                _tr.right);

        Vector3 up =
            Vector3.Project(
                _velocity,
                _tr.up);

        forward *=
            Mathf.Clamp01(
                1f - ForwardDrag * dt);

        right *=
            Mathf.Clamp01(
                1f - SideDrag * dt);

        up *=
            Mathf.Clamp01(
                1f - VerticalDrag * dt);

        _velocity =
            forward +
            right +
            up;

        /*
         * Horizontal speed limit.
         * Vertical velocity is left untouched.
         */

        Vector3 horizontal =
            Vector3.ProjectOnPlane(
                _velocity,
                Vector3.up);

        float speed =
            horizontal.magnitude;

        if (speed > MaxSpeed)
        {
            horizontal *=
                MaxSpeed / speed;

            _velocity =
                horizontal +
                Vector3.up *
                _velocity.y;
        }
    }

    private void Integrate(float dt)
    {
        _tr.position +=
            _velocity * dt;
    }

#if UNITY_EDITOR
    private void OnDrawGizmos()
    {
        Gizmos.color = Color.yellow;
        Gizmos.DrawWireSphere(
            TargetPosition,
            1f);

        if (!Application.isPlaying)
            return;

        Gizmos.color = Color.green;
        Gizmos.DrawRay(
            _tr.position,
            _desiredThrust.normalized * 8f);

        Gizmos.color = Color.blue;
        Gizmos.DrawRay(
            _tr.position,
            _tr.up * 6f);

        Gizmos.color = Color.red;
        Gizmos.DrawRay(
            _tr.position,
            _velocity * 0.25f);
    }
#endif
}